set1:
  circlet: "\u867A\u96F7\u4E4B\u59FF"
  flower: "\u751F\u7075\u4E4B\u534E"
  goblet: "\u7ED3\u5951\u4E4B\u523B"
  plume: "\u6F5C\u5149\u7247\u7FBD"
  sands: "\u9633\u8F94\u4E4B\u9057"
  setname: VermillionHereafter
set2:
  circlet: "\u6D6E\u6EAF\u4E4B\u73CF"
  flower: "\u9B42\u9999\u4E4B\u82B1"
  goblet: "\u6D8C\u6CC9\u4E4B\u76CF"
  plume: "\u5782\u7389\u4E4B\u53F6"
  sands: "\u795D\u7940\u4E4B\u51ED"
  setname: EchoesOfAnOffering
